jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/first_boot
  username: postgres
  password: postgres

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  hbm2ddl:
    auto: update

entitymanager:
  packagesToScan: com.example.integrationtestboot.entity
